### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by MephestoKhaan** [JoshLmao/Spotify4Unity#1]
Hi! Just came across this and I think it is an amazing idea.
What is stopping you from supporting Android? Do you have it in mind / rough date?

**Comment by JoshLmao** [comment]
Hey! Thanks but keep in mind I've only created a nice way to interface with the [Spotify .NET API](https://github.com/JohnnyCrazy/SpotifyAPI-NET) & made some UI to use that

The only thing stopping this from working on iOS/Android is the authentification method used in the .NET API. Recently, that project got a big change (in v3.0) so it only supports desktop

However, if it ever gets updated to support mobile, i'll make sure it works with my tools straight away!

**Comment by JoshLmao** [comment]
Okay, that looks promising, thanks for sharing. And yes, I'd be happy to hear what you find ;D

**Comment by timendez** [comment]
@MephestoKhaan @JoshLmao Any updates on this issue?

**Comment by JoshLmao** [comment]
Unfortunately not at the moment. I actually have a couple days spare right now and think I can create a way for this to be possible. I'll update if I find anything

Edit: Although I'm not hopeful or promising I will find a way. We'll see

**Comment by timendez** [comment]
Awesome, thanks man!

**Comment by JoshLmao** [comment]
Okay, so actually some really good news! I've figured out a way to use Spotify's Implicit Grant Flow authorization on Android however it come's with some setup. 

I'm gonna spend some time thinking of how to make this as nice as possible for people and get an update out. Don't expect anything soon and any updates, I'll put out on my Twitter ☺

**Comment by timendez** [comment]
Thanks @JoshLmao!

**Comment by JoshLmao** [comment]
I found this [blog post](http://oferei.com/2013/06/serverless-instagram-authentication/) with a way of doing serverless OAuth on Android and have implemented it in v1.3. However, it's not perfect since it uses the Implicit Grant auth flow which requires re-auth every 60 mins.

I plan on changing it in the future to how PC auth flow works but for short term, I think this is the best solution. I've also updated [the wiki with a guide](https://github.com/JoshLmao/Spotify4Unity/wiki/Android-Authorization) if you're eager to take a look.

I've submitted v1.3 to the Asset Store now and should be approved within the next couple days.
